forge "http://forge.puppetlabs.com"

mod 'puppetlabs-apt', '4.5.1'

mod 'puppetlabs-apache',
	:git	=> "http://github.com/puppetlabs/puppetlabs-apache.git"
  
mod 'puppetlabs-mysql',
	:git	=> "http://github.com/puppetlabs/puppetlabs-mysql.git"
	
mod 'jlondon-phpmyadmin', '1.3.0'

mod 'willdurand/nodejs', '2.0.1'
	
mod 'puppet-devenv',
	:git	=> "https://github.com/iatanasov77/puppet-devenv.git"
